CREATE TABLE CLIENT_TB(
	CLIENTID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	REGISTRATIONDATE DATETIME NOT NULL,
	PRIMARY KEY(CLIENTID))
GO

SELECT * FROM CLIENT_TB
GO